- name: ansible-vault playbook
  hosts: local
  connection: yes
  become: yes
  vars_files:
    - 01-secratefile
  tasks:
  - name: ansible-vault
    ansible.builtin.debug:
      msg: "user name is: {{ user }}, Passwd is: {{ passwd }}"