- name: Display disk size
  hosts: local
  connection: local
  become: yes

  tasks:
    - name: Check /var disk usage
      ansible.builtin.shell: df -h /var | awk 'NR==2 {print $5}'
      register: disk
      changed_when: false

    - name: Display disk high
      ansible.builtin.debug:
        msg: "Disk is high"
      when: disk.stdout | int > 70