- name: display disk size
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: display disk
    ansible.builtin.command: df -h /var
    register: disk

  - name: display disk high
    ansible.builtin.debug:
      msg: "disk is high"
    when: " '70%' in disk.stdout "