#!/bin/bash

PERSON1="PERAIAH"
PERSON2="VINAY"

echo "$PERSON1:: Hi $PERSON2 HOW ARE YOU MAN!"
echo "$PERSON2:: HELLO IAM DOING GOOD $PERSON1"
echo "$PERSON1:: WHAT ELSE $PERSON2 TELL ME SOMETHING"
echo "$PERSON2:: NOTHING $PERSON2 I DONT HAVE NO MATTER"