- name: display disk information
  hosts: local
  connection: local
  become: yes
  
  tasks:
  - name: command
    ansible.builtin.command: df -h 
    register: disk_size

  - name: check disk disk size 
    ansible.builtin.debug:
       var: disk_size.stdout 