- name: display disk information
  hosts: local
  connection: local
  become: yes
  
  tasks:
  - name: command
    ansible.builtin.command:
      command: df -h 
      register: disk_size

  - name: check disk disk size 
    ansible.builtin.debud:
      variable: disk_size