PERSON1="$1"
PERSON2="$2"

echo "$PERSON1:: Hi $PERSON2 HOW ARE YOU MAN!"
echo "$PERSON2:: HELLO IAM DOING GOOD $PERSON1"
echo "$PERSON1:: WHAT ELSE $PERSON2 TELL ME SOMETHING"
echo "$PERSON2:: NOTHING $PERSON1 I DONT HAVE NO MATTER"